custom_configurations:
  Laptop:
    Sharp Corporation 0x1515 0x00000000:
      active: true
      resolution:
        - 1920
        - 1200
      position:
        - 0
        - 0
      rotation: normal
      scale: 1.0
      workspaces:
        - "1"
        - music
default_configurations:
  ? - Dell Inc. DELL S3422DWG 48LXSH3
    - "Goldstar Company Ltd LG FULL HD "
    - Sharp Corporation 0x1515 0x00000000
  : "Goldstar Company Ltd LG FULL HD ":
      active: true
      resolution:
        - 1080
        - 1920
      position:
        - 3440
        - 230
      rotation: "90"
      refresh_rate: 60000
      scale: 0.95
      workspaces:
        - music
    Dell Inc. DELL S3422DWG 48LXSH3:
      active: true
      resolution:
        - 3621
        - 1515
      refresh_rate: 143975
      workspaces:
        - "1"
        - "3"
        - "4"
    Sharp Corporation 0x1515 0x00000000:
 