custom_configurations:
  # Cusom configurations are identified by name
  Home Setup:
    ...
  Work Setup:
    ...
default_configurations:
  # Default configurations are identified by a set of connected displays
  ? [
      Dell Inc. DELL S3422DWG 48LXSH3,
      "Goldstar Company Ltd LG FULL HD ",
      Sharp Corporation 0x1515 0x00000000,
    ]
  : "Goldstar Company Ltd LG FULL HD ":
      active: true
      resolution: [1920, 1080]
      position: [3440, 230]
      rotation: "90"
      refresh_rate: 60000
      scale: 0.95
      workspaces: [music, 1, 2, 3, 4]
    Dell Inc. DELL S3422DWG 48LXSH3:
      ...
    Sharp Corporation 0x1515 0x00000000:
      ...